### ISSUE TITLE
docker-compose file required 

### ISSUE THREAD

**Issue by tanav2202** [tanav2202/TBGAN-FastAPI#4]

**Comment by Ansh-Sarkar** [comment]
Hey @tanav2202 ! I think I can take up this issue.

## Proposals

- [x] Add a ```requirements.txt``` file to the repository in order to facilitate easier project setup
- [x] Add instructions in the ```README.md``` file detailing steps on creating Virtual Envs and Project Setup
- [x] Create a ```Dockerfile``` and a ```docker-compose``` file for containerization of the project.

Do assign me this issue if you think these would be valuable additions to this project. Thanks !

**Comment by tanav2202** [comment]
Hey @Ansh-Sarkar,
@vedant-204   is also attempting to do the same work. You can also discuss it with him. I am open to you both splitting the job if need be. That is why I won't assign the issue to either of you. 
You can make a pull request if I find it useful I will merge it.

**Comment by vedant-204** [comment]
@Ansh-Sarkar I have created the Dockerfile and requirements.txt. 
I am writing a docker-compose file
Can you update the README.md accordingly, once I am done ?

**Comment by tanav2202** [comment]
Completed by @vedant-204  (that was quick lmao)
